language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"
install:
  - pip install https://github.com/nixnodes/pydle/archive/master.zip
  - pip install .
# command to run tests
script: python runtests.py
